### ISSUE TITLE
Ask the owner of Youtube channel to enable Video Playback on websites

### ISSUE THREAD

**Issue by Jat-coder** [AWS-Cloud-Community-LPU/Official-Website#46]
In Events tab we get an error, saying:
Playback on other websites has been disabled by the video owner.

**Comment by Jat-coder** [comment]
![image](https://user-images.githubusercontent.com/79071077/120878943-6d78a700-c5dd-11eb-99fa-a542248538a8.png)
@prtk2001 @garvit-joshi

**Comment by garvit-joshi** [comment]
Video Playback has been enabled in our youtube channel, However, the latest youtube video was hosted by AWS User Group Jaipur. Let me see if they can turn on the Embedding on their youtube videos.

**Comment by Jat-coder** [comment]
Why don't we just upload the latest video on our channel, and our link in the code?
@garvit-joshi

**Comment by garvit-joshi** [comment]
I had a talk with AWS User Group Jaipur. The issue will be resolved by today.

**Comment by garvit-joshi** [comment]
Issue Resolved!!
